import type { JobHandler, JobPayload } from "@/lib/jobs/types";
import { db } from "@/lib/db";

interface AISummaryPayload extends JobPayload {
  projectId: string;
  variant: string;
}

export const generateAISummaryJob: JobHandler<AISummaryPayload> = {
  type: "generate-ai-summary",

  async handle(payload, jobId) {
    const { organizationId, actorId, projectId, variant } = payload;

    console.info("[JOB:ai-summary] Starting", { jobId, projectId, variant });

    const project = await db.project.findFirst({
      where: { id: projectId, organizationId },
      include: {
        workEvents: { orderBy: { occurredAt: "desc" }, take: 50 },
        evidences: { orderBy: { createdAt: "desc" }, take: 20 },
        riskFlags: { where: { resolved: false } },
      },
    });

    if (!project) {
      throw new Error(`Project ${projectId} not found in org ${organizationId}`);
    }

    const eventCount = project.workEvents.length;
    const evidenceCount = project.evidences.length;
    const openRisks = project.riskFlags.length;

    const summary = [
      `Project "${project.name}" has ${eventCount} recent work events and ${evidenceCount} evidence artifacts.`,
      openRisks > 0 ? `There are ${openRisks} unresolved risk flags requiring attention.` : "No open risk flags.",
      `Status: ${project.status}. Generated by ${variant} variant.`,
    ].join(" ");

    await db.aIReport.create({
      data: {
        organizationId,
        projectId,
        variant,
        title: `AI Summary — ${project.name}`,
        summary,
        generatedBy: actorId,
        model: "internal-v1",
        promptVersion: "1.0",
      },
    });

    console.info("[JOB:ai-summary] Completed", { jobId, projectId });
  },
};
